apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-00-d5708dcc9026/my-repository/sample-app-prod:v2.0
        ports:
        - containerPort: 8080
